enum ActionTypes {
  SET_MSG = "SET_MSG",
  SET_IS_DARK_THEME = "SET_IS_DARK_THEME",
  SET_SELECTED_LANG = "SET_SELECTED_LANG",
  SET_ACCESS_TOKEN = "SET_ACCESS_TOKEN",
  SET_CONNECTED_USER = "SET_CONNECTED_USER",
}

export default ActionTypes;
